name: BlueskyPlugin
version: 1.0
main: com.example.blueskyplugin.BlueskyPlugin
api-version: '1.21'
commands:
  bsky:
    description: Blueskyのコマンド
    usage: /bsky <login|post|tl|feed>
    permission: bluesky.use