name: BlueskyPlugin
version: 1.2
main: com.example.blueskyplugin.BlueskyPlugin
api-version: '1.21'
commands:
  bsky:
    description: Bluesky commands
    usage: /bsky <login|post|tl|feed|lang>
    permission: bluesky.use
